# Generated by Django 5.2 on 2025-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_files',
            field=models.FileField(blank=True, null=True, upload_to='mentors/'),
        ),
    ]
