# Generated by Django 5.2 on 2026-02-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Mensaje de texto'), ('advice', 'Consejo/Asesoría'), ('feedback', 'Retroalimentación'), ('milestone', 'Hito del proyecto'), ('resource', 'Recurso compartido'), ('system', 'Mensaje del sistema')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='related_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource'),
        ),
    ]
