# Generated by Django 5.2 on 2025-04-22 17:01

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_uploaded_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_files',
        ),
    ]
