# Generated by Django 5.2 on 2025-04-26 00:46

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_uploaded_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
