# Generated by Django 5.2 on 2026-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profitability_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo estimado para que el proyecto empiece a generar rentabilidad', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='profitability_unit',
            field=models.CharField(blank=True, choices=[('meses', 'Meses'), ('años', 'Años')], default='meses', max_length=10),
        ),
    ]
