# Generated by Django 5.2 on 2026-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_profitability_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
