# Generated by Django 5.2 on 2025-04-26 01:17

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_birth_date_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
