# Generated by Django 5.2 on 2025-04-30 00:56

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
