# Generated by Django 5.2 on 2025-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_investment_is_accepted_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
