# Generated by Django 5.2 on 2026-03-02 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ai_project_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraude', 'Fraude o estafa'), ('spam', 'Spam o contenido repetitivo'), ('falso', 'Información falsa o engañosa'), ('inapropiado', 'Contenido inapropiado u ofensivo'), ('duplicado', 'Cuenta o proyecto duplicado'), ('otro', 'Otro')], max_length=20)),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En revisión'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=15)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='core.project')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-created_at'],
            },
        ),
    ]
