# Generated by Django 5.2 on 2025-04-30 02:28

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
