# Generated by Django 5.2 on 2026-03-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('signed_uploaded', 'Firmado y Subido')], default='generated', max_length=20)),
                ('signed_document', models.FileField(blank=True, help_text='Documento firmado subido por el inversionista', null=True, upload_to='contracts/signed/%Y/%m/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.investment')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
