# Generated by Django 5.2 on 2025-04-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
