# Generated by Django 5.2 on 2025-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='initiated_by',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('entrepreneur', 'Entrepreneur')], default='mentor', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
